Repository gul-cpp/gul14, pull requests merged in 2024-03, with the labels that each got.

#84 ThreadPool: Fixup: Export missing symbols
  include/gul14/ThreadPool.h
  tests/meson.build
Labels: bug

#85 ThreadPool: Correct docs
  include/gul14/ThreadPool.h
Labels: documentation

#89 ThreadPool::TaskHandle: Add default constructor
  include/gul14/ThreadPool.h
  tests/test_ThreadPool.cc
Labels: enhancement

#88 CI: Drop Ubuntu 16.04
  .gitlab-ci/build.yml
Labels: ci
